// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: rbac/implementation.proto

package rbac

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_implementation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_implementation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_rbac_implementation_proto_rawDescGZIP(), []int{0}
}

type EmptyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_implementation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_implementation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_rbac_implementation_proto_rawDescGZIP(), []int{1}
}

type PermissionDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Effect string `protobuf:"bytes,3,opt,name=effect,proto3" json:"effect,omitempty"`
}

func (x *PermissionDefinition) Reset() {
	*x = PermissionDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_implementation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionDefinition) ProtoMessage() {}

func (x *PermissionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_implementation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionDefinition.ProtoReflect.Descriptor instead.
func (*PermissionDefinition) Descriptor() ([]byte, []int) {
	return file_rbac_implementation_proto_rawDescGZIP(), []int{2}
}

func (x *PermissionDefinition) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *PermissionDefinition) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermissionDefinition) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

type AddChildSubjectToParentSubjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Child  string `protobuf:"bytes,1,opt,name=child,proto3" json:"child,omitempty"`
	Parent string `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
}

func (x *AddChildSubjectToParentSubjectRequest) Reset() {
	*x = AddChildSubjectToParentSubjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_implementation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddChildSubjectToParentSubjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddChildSubjectToParentSubjectRequest) ProtoMessage() {}

func (x *AddChildSubjectToParentSubjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_implementation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddChildSubjectToParentSubjectRequest.ProtoReflect.Descriptor instead.
func (*AddChildSubjectToParentSubjectRequest) Descriptor() ([]byte, []int) {
	return file_rbac_implementation_proto_rawDescGZIP(), []int{3}
}

func (x *AddChildSubjectToParentSubjectRequest) GetChild() string {
	if x != nil {
		return x.Child
	}
	return ""
}

func (x *AddChildSubjectToParentSubjectRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type RemoveChildSubjectFromParentSubjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Child  string `protobuf:"bytes,1,opt,name=child,proto3" json:"child,omitempty"`
	Parent string `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
}

func (x *RemoveChildSubjectFromParentSubjectRequest) Reset() {
	*x = RemoveChildSubjectFromParentSubjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_implementation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveChildSubjectFromParentSubjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveChildSubjectFromParentSubjectRequest) ProtoMessage() {}

func (x *RemoveChildSubjectFromParentSubjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_implementation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveChildSubjectFromParentSubjectRequest.ProtoReflect.Descriptor instead.
func (*RemoveChildSubjectFromParentSubjectRequest) Descriptor() ([]byte, []int) {
	return file_rbac_implementation_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveChildSubjectFromParentSubjectRequest) GetChild() string {
	if x != nil {
		return x.Child
	}
	return ""
}

func (x *RemoveChildSubjectFromParentSubjectRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type RemoveSubjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
}

func (x *RemoveSubjectRequest) Reset() {
	*x = RemoveSubjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_implementation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveSubjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubjectRequest) ProtoMessage() {}

func (x *RemoveSubjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_implementation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubjectRequest.ProtoReflect.Descriptor instead.
func (*RemoveSubjectRequest) Descriptor() ([]byte, []int) {
	return file_rbac_implementation_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveSubjectRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type CreatePolicyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject    string                `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Permission *PermissionDefinition `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
}

func (x *CreatePolicyRequest) Reset() {
	*x = CreatePolicyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_implementation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyRequest) ProtoMessage() {}

func (x *CreatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_implementation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyRequest.ProtoReflect.Descriptor instead.
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_rbac_implementation_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePolicyRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreatePolicyRequest) GetPermission() *PermissionDefinition {
	if x != nil {
		return x.Permission
	}
	return nil
}

type RemovePolicyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject    string                `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Permission *PermissionDefinition `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
}

func (x *RemovePolicyRequest) Reset() {
	*x = RemovePolicyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_implementation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePolicyRequest) ProtoMessage() {}

func (x *RemovePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_implementation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePolicyRequest.ProtoReflect.Descriptor instead.
func (*RemovePolicyRequest) Descriptor() ([]byte, []int) {
	return file_rbac_implementation_proto_rawDescGZIP(), []int{7}
}

func (x *RemovePolicyRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RemovePolicyRequest) GetPermission() *PermissionDefinition {
	if x != nil {
		return x.Permission
	}
	return nil
}

type CreatePoliciesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject     string                  `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Permissions []*PermissionDefinition `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
}

func (x *CreatePoliciesRequest) Reset() {
	*x = CreatePoliciesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_implementation_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePoliciesRequest) ProtoMessage() {}

func (x *CreatePoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_implementation_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePoliciesRequest.ProtoReflect.Descriptor instead.
func (*CreatePoliciesRequest) Descriptor() ([]byte, []int) {
	return file_rbac_implementation_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePoliciesRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreatePoliciesRequest) GetPermissions() []*PermissionDefinition {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type RemovePoliciesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject     string                  `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Permissions []*PermissionDefinition `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
}

func (x *RemovePoliciesRequest) Reset() {
	*x = RemovePoliciesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_implementation_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePoliciesRequest) ProtoMessage() {}

func (x *RemovePoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_implementation_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePoliciesRequest.ProtoReflect.Descriptor instead.
func (*RemovePoliciesRequest) Descriptor() ([]byte, []int) {
	return file_rbac_implementation_proto_rawDescGZIP(), []int{9}
}

func (x *RemovePoliciesRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RemovePoliciesRequest) GetPermissions() []*PermissionDefinition {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type HasPermissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject    string                                     `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Permission *HasPermissionRequest_PermissionDefinition `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
}

func (x *HasPermissionRequest) Reset() {
	*x = HasPermissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_implementation_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPermissionRequest) ProtoMessage() {}

func (x *HasPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_implementation_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPermissionRequest.ProtoReflect.Descriptor instead.
func (*HasPermissionRequest) Descriptor() ([]byte, []int) {
	return file_rbac_implementation_proto_rawDescGZIP(), []int{10}
}

func (x *HasPermissionRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *HasPermissionRequest) GetPermission() *HasPermissionRequest_PermissionDefinition {
	if x != nil {
		return x.Permission
	}
	return nil
}

type HasPermissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Has bool `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
}

func (x *HasPermissionResponse) Reset() {
	*x = HasPermissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_implementation_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPermissionResponse) ProtoMessage() {}

func (x *HasPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_implementation_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPermissionResponse.ProtoReflect.Descriptor instead.
func (*HasPermissionResponse) Descriptor() ([]byte, []int) {
	return file_rbac_implementation_proto_rawDescGZIP(), []int{11}
}

func (x *HasPermissionResponse) GetHas() bool {
	if x != nil {
		return x.Has
	}
	return false
}

type HasPermissionRequest_PermissionDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *HasPermissionRequest_PermissionDefinition) Reset() {
	*x = HasPermissionRequest_PermissionDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rbac_implementation_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasPermissionRequest_PermissionDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPermissionRequest_PermissionDefinition) ProtoMessage() {}

func (x *HasPermissionRequest_PermissionDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_rbac_implementation_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPermissionRequest_PermissionDefinition.ProtoReflect.Descriptor instead.
func (*HasPermissionRequest_PermissionDefinition) Descriptor() ([]byte, []int) {
	return file_rbac_implementation_proto_rawDescGZIP(), []int{10, 0}
}

func (x *HasPermissionRequest_PermissionDefinition) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *HasPermissionRequest_PermissionDefinition) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_rbac_implementation_proto protoreflect.FileDescriptor

var file_rbac_implementation_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x62, 0x61, 0x63, 0x2f, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x62, 0x75, 0x74,
	0x74, 0x72, 0x65, 0x73, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5e, 0x0a, 0x14, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x22, 0x55, 0x0a, 0x25, 0x41, 0x64, 0x64, 0x43, 0x68, 0x69,
	0x6c, 0x64, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x50, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x63, 0x68, 0x69, 0x6c, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x22, 0x5a, 0x0a,
	0x2a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x53, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x68, 0x69, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x68, 0x69, 0x6c,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x22, 0x30, 0x0a, 0x14, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x6f, 0x0a, 0x13, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x3e, 0x0a, 0x0a,
	0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x6f, 0x0a, 0x13,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x3e, 0x0a,
	0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x73, 0x0a,
	0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x40, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73,
	0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x73, 0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x40, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x75, 0x74,
	0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xcd, 0x01, 0x0a, 0x14, 0x48, 0x61, 0x73, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x53, 0x0a, 0x0a, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33,
	0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x48, 0x61, 0x73, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a,
	0x46, 0x0a, 0x14, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x29, 0x0a, 0x15, 0x48, 0x61, 0x73, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x68, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x68,
	0x61, 0x73, 0x32, 0x8c, 0x06, 0x0a, 0x0b, 0x52, 0x62, 0x61, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x47, 0x0a, 0x12, 0x45, 0x6e, 0x73, 0x75, 0x72, 0x65, 0x52, 0x62, 0x61, 0x63,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x2e, 0x62, 0x75, 0x74, 0x74, 0x72,
	0x65, 0x73, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x1e, 0x41,
	0x64, 0x64, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x6f,
	0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x2f, 0x2e,
	0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x68, 0x69, 0x6c,
	0x64, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x76, 0x0a, 0x23, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x46,
	0x72, 0x6f, 0x6d, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x34, 0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x72,
	0x6f, 0x6d, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73,
	0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4a, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x12, 0x1e, 0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a,
	0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x1d, 0x2e,
	0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x62,
	0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x1d, 0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65,
	0x73, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73,
	0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4c, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x69, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4c, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65,
	0x73, 0x12, 0x1f, 0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a,
	0x0d, 0x48, 0x61, 0x73, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e,
	0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x48, 0x61, 0x73, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x62, 0x75, 0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x48, 0x61, 0x73, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x65, 0x72, 0x61, 0x6a, 0x73, 0x61, 0x68, 0x65, 0x62, 0x64, 0x61, 0x72, 0x2f, 0x62, 0x75,
	0x74, 0x74, 0x72, 0x65, 0x73, 0x73, 0x2d, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rbac_implementation_proto_rawDescOnce sync.Once
	file_rbac_implementation_proto_rawDescData = file_rbac_implementation_proto_rawDesc
)

func file_rbac_implementation_proto_rawDescGZIP() []byte {
	file_rbac_implementation_proto_rawDescOnce.Do(func() {
		file_rbac_implementation_proto_rawDescData = protoimpl.X.CompressGZIP(file_rbac_implementation_proto_rawDescData)
	})
	return file_rbac_implementation_proto_rawDescData
}

var file_rbac_implementation_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_rbac_implementation_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil),                               // 0: buttress.EmptyRequest
	(*EmptyResponse)(nil),                              // 1: buttress.EmptyResponse
	(*PermissionDefinition)(nil),                       // 2: buttress.PermissionDefinition
	(*AddChildSubjectToParentSubjectRequest)(nil),      // 3: buttress.AddChildSubjectToParentSubjectRequest
	(*RemoveChildSubjectFromParentSubjectRequest)(nil), // 4: buttress.RemoveChildSubjectFromParentSubjectRequest
	(*RemoveSubjectRequest)(nil),                       // 5: buttress.RemoveSubjectRequest
	(*CreatePolicyRequest)(nil),                        // 6: buttress.CreatePolicyRequest
	(*RemovePolicyRequest)(nil),                        // 7: buttress.RemovePolicyRequest
	(*CreatePoliciesRequest)(nil),                      // 8: buttress.CreatePoliciesRequest
	(*RemovePoliciesRequest)(nil),                      // 9: buttress.RemovePoliciesRequest
	(*HasPermissionRequest)(nil),                       // 10: buttress.HasPermissionRequest
	(*HasPermissionResponse)(nil),                      // 11: buttress.HasPermissionResponse
	(*HasPermissionRequest_PermissionDefinition)(nil),  // 12: buttress.HasPermissionRequest.PermissionDefinition
}
var file_rbac_implementation_proto_depIdxs = []int32{
	2,  // 0: buttress.CreatePolicyRequest.permission:type_name -> buttress.PermissionDefinition
	2,  // 1: buttress.RemovePolicyRequest.permission:type_name -> buttress.PermissionDefinition
	2,  // 2: buttress.CreatePoliciesRequest.permissions:type_name -> buttress.PermissionDefinition
	2,  // 3: buttress.RemovePoliciesRequest.permissions:type_name -> buttress.PermissionDefinition
	12, // 4: buttress.HasPermissionRequest.permission:type_name -> buttress.HasPermissionRequest.PermissionDefinition
	0,  // 5: buttress.RbacService.EnsureRbacInstance:input_type -> buttress.EmptyRequest
	3,  // 6: buttress.RbacService.AddChildSubjectToParentSubject:input_type -> buttress.AddChildSubjectToParentSubjectRequest
	4,  // 7: buttress.RbacService.RemoveChildSubjectFromParentSubject:input_type -> buttress.RemoveChildSubjectFromParentSubjectRequest
	5,  // 8: buttress.RbacService.RemoveSubject:input_type -> buttress.RemoveSubjectRequest
	6,  // 9: buttress.RbacService.CreatePolicy:input_type -> buttress.CreatePolicyRequest
	7,  // 10: buttress.RbacService.RemovePolicy:input_type -> buttress.RemovePolicyRequest
	8,  // 11: buttress.RbacService.CreatePolicies:input_type -> buttress.CreatePoliciesRequest
	9,  // 12: buttress.RbacService.RemovePolicies:input_type -> buttress.RemovePoliciesRequest
	10, // 13: buttress.RbacService.HasPermission:input_type -> buttress.HasPermissionRequest
	1,  // 14: buttress.RbacService.EnsureRbacInstance:output_type -> buttress.EmptyResponse
	1,  // 15: buttress.RbacService.AddChildSubjectToParentSubject:output_type -> buttress.EmptyResponse
	1,  // 16: buttress.RbacService.RemoveChildSubjectFromParentSubject:output_type -> buttress.EmptyResponse
	1,  // 17: buttress.RbacService.RemoveSubject:output_type -> buttress.EmptyResponse
	1,  // 18: buttress.RbacService.CreatePolicy:output_type -> buttress.EmptyResponse
	1,  // 19: buttress.RbacService.RemovePolicy:output_type -> buttress.EmptyResponse
	1,  // 20: buttress.RbacService.CreatePolicies:output_type -> buttress.EmptyResponse
	1,  // 21: buttress.RbacService.RemovePolicies:output_type -> buttress.EmptyResponse
	11, // 22: buttress.RbacService.HasPermission:output_type -> buttress.HasPermissionResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_rbac_implementation_proto_init() }
func file_rbac_implementation_proto_init() {
	if File_rbac_implementation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rbac_implementation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_implementation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_implementation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_implementation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddChildSubjectToParentSubjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_implementation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveChildSubjectFromParentSubjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_implementation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveSubjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_implementation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePolicyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_implementation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePolicyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_implementation_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePoliciesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_implementation_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePoliciesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_implementation_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasPermissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_implementation_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasPermissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rbac_implementation_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasPermissionRequest_PermissionDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rbac_implementation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rbac_implementation_proto_goTypes,
		DependencyIndexes: file_rbac_implementation_proto_depIdxs,
		MessageInfos:      file_rbac_implementation_proto_msgTypes,
	}.Build()
	File_rbac_implementation_proto = out.File
	file_rbac_implementation_proto_rawDesc = nil
	file_rbac_implementation_proto_goTypes = nil
	file_rbac_implementation_proto_depIdxs = nil
}
